   version: '3'
   services:
     vue:
       build:
        context: . 
        dockerfile: Dockerfile
       volumes:
         - .:/app
       ports:
         - 8080:5173
       command: npm run dev
